name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects (V2).'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true
  project-url:
    description: 'The URL of the Github Project.'
    required: true
  get-items:
    description: 'Selectors for the items you want to fetch.'
  read-fields:
    description: 'Selectors for the fields you want to read.'
  read-items:
    description: 'Selectors for the items you want to read the fields of.'
  add-items:
    description: 'Selectors for the items you want to add to the project.'
  edit-fields:
    description: 'Selectors for the fields you want to edit.'

outputs:
  some-output:
    description: "Output testing"
    value: ${{ steps.outputGen.outputs.something }}

runs:
  using: "composite"
  steps:
    - run: |
        Write-Output "URL input : ${{ inputs.project-url }}."
      shell: pwsh
    - id: outputGen
      run: echo "::set-output name=something::tralala"
      shell: pwsh
    - run: Write-Output "${{ github.action_path }}" >> $GITHUB_PATH
      shell: pwsh
    - run: ${{ github.action_path }}/src/getFieldIds.ps1
      shell: pwsh