name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        if ($${{ runner.os == 'Linux' }}) {
          $path = '/home/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'macOS' }}) {
          $path = '/Users/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'Windows' }}) {
          $path = 'C:\Users\runneradmin\Documents\PowerShell\Modules\'
        } else {
          throw 'Unknown OS: ${{runner.os}}.'
        }

        New-Item -ItemType Directory -Path "$path/ProjectAccess/"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$path/ProjectAccess/"
      shell: pwsh

    # - run: echo ${{ toJSON(env) }}
    #   shell: bash