name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        if ($${{ runner.os == 'Linux' }}) {
          $path = '/home/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'macOS' }}) {
          $path = '/Users/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'Windows' }}) {
          $path = 'C:\Users\runneradmin\Documents\PowerShell\Modules\'
        } else {
          throw 'Unknown OS: ${{runner.os}}.'
        }

        New-Item -ItemType Directory -Path "$path/ProjectAccess/"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$path/ProjectAccess/"

        $token = '${{inputs.github-token}}';
        if ('' -eq $token) { $token = '${{env.PA_GH_TOKEN}}'}
        if ('' -ne $token) { "PA_GH_TOKEN=$token" >> $Env:GITHUB_ENV }

        $o = [AppDomain]::CurrentDomain.GetAssemblies() # helps for debug
        $s = ''
        foreach ($v in $o) {
          $s += "$($v.Location)`n"
        }
        Write-Host "$s"
      shell: pwsh

    # - run: echo ${{ toJSON(env) }}
    #   shell: bash