name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        Import-Module ${{ github.action_path }}/src/ProjectAccess.psm1
        Set-GithubAuth -Token ${{ inputs.github-token }}
      shell: pwsh