name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        New-Item -ItemType Directory -Path "$home\PowerShell\Modules\ProjectAccess\"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$home\PowerShell\Modules\ProjectAccess\"

        $sep1 = [System.IO.Path]::PathSeparator
        $sep2 = [System.IO.Path]::DirectorySeparatorChar
        $Env:PSModulePath += "{0}$home{1}PowerShell{1}Modules{1}ProjectAccess{1}" -f @($sep1,$sep2)
        Write-Host $Env:PSModulePath
      shell: pwsh