name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token.

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        if ($${{ runner.os == 'Linux' }}) {
          $path = '/home/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'macOS' }}) {
          $path = '/Users/runner/.local/share/powershell/Modules/'
        } elseif ($${{ runner.os == 'Windows' }}) {
          $path = 'C:\Users\runneradmin\Documents\PowerShell\Modules\'
        } else {
          throw 'Unknown OS: ${{runner.os}}.'
        }

        New-Item -ItemType Directory -Path "$path/ProjectAccess/"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$path/ProjectAccess/"
        Write-Host "Module installed in $path/ProjectAccess/"

        $token = '${{inputs.github-token}}';
        if ('' -eq $token) { $token = '${{env.PA_GH_TOKEN}}'}
        if ('' -ne $token) { "PA_GH_TOKEN=$token" >> $Env:GITHUB_ENV }
      shell: pwsh