name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        New-Item -ItemType Directory -Path "$home\PowerShell\Modules\ProjectAccess\"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$home\PowerShell\Modules\ProjectAccess\"

        $sep1 = [System.IO.Path]::PathSeparator
        $sep2 = [System.IO.Path]::DirectorySeparatorChar
        $path = "{0}$home{1}PowerShell{1}Modules{1}ProjectAccess{1}" -f @($sep1,$sep2)
        [System.Environment]::SetEnvironmentVariable('PSModulePath',($Env:PSModulePath+$path))
        Write-Host $Env:PSModulePath

        $var = $($Env:PSModulePath+$path)
        echo "var: $var"
        echo "PSModulePath=$var" >> $GITHUB_ENV
      shell: pwsh

    - run: Write-Host ${{ toJSON(env) }}
      shell: pwsh