name: 'Project Access'
author: 'NeroGM'
description: 'Read/Edit Github Projects.'

inputs:
  github-token:
    description: A Personal Access Token with at least "repo" and "project" scope.
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment
      run: |
        New-Item -ItemType Directory -Path "$home\Documents\PowerShell\Modules\ProjectAccess\"
        Copy-Item '${{ github.action_path }}\src\*' -Destination "$home\Documents\PowerShell\Modules\ProjectAccess\"
      shell: pwsh